# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d31de03d8acbee4fde2d232959e5bfa75b0f8c27f68a0846d669c23ca2918207fd386c5df123d706b6f780d0941eeb5e7eac25a2ae12cf055e7fdd76e67a55ba

test:
  secret_key_base: 4df8c8aa039e0b9c6623d134e4e4253dbfe8fc532c651d1268de902405b5ec7d6cf6c990871c20a54f4815d406118863c3248a8c7acb677751c857ce3ba0c881

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
